# Generated by Django 3.2 on 2021-07-07 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BadmintonItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_item', models.CharField(max_length=200)),
                ('item_type', models.CharField(choices=[('bat', 'bat'), ('ball', 'ball'), ('Badminton net', 'Badminton net'), ('pad', 'pad'), ('shoes', 'shoes'), ('corke', 'corke'), ('fullkit', 'fullkit'), ('cap', 'cap'), ('jersy', 'jersy'), ('select', 'select')], default='select', max_length=100)),
                ('item_image', models.ImageField(upload_to='sports/badminton/')),
                ('note', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('warranty', models.CharField(max_length=100)),
                ('Offer', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CarromChessItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_item', models.CharField(max_length=200)),
                ('item_type', models.CharField(choices=[('chess board', 'chess board'), ('carom board', 'carom board'), ('chess coins', 'chess coins'), ('powder', 'powder'), ('stricker', 'stricker'), ('carom coins', 'carom coins'), ('chess fullkit', 'chess fullkit'), ('cap', 'cap'), ('jersy', 'jersy'), ('select', 'select'), ('carom fullkit', 'carom fullkit')], default='select', max_length=100)),
                ('item_image', models.ImageField(upload_to='sports/caromchess/')),
                ('note', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('warranty', models.CharField(max_length=100)),
                ('Offer', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CricketItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_item', models.CharField(max_length=200)),
                ('item_type', models.CharField(choices=[('bat', 'bat'), ('ball', 'ball'), ('helmet', 'helmet'), ('pad', 'pad'), ('shoes', 'shoes'), ('stumb', 'stumb'), ('fullkit', 'fullkit'), ('cap', 'cap'), ('glovse', 'glovse'), ('jersy', 'jersy'), ('select', 'select')], default='select', max_length=100)),
                ('item_image', models.ImageField(upload_to='sports/cricket/')),
                ('note', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('warranty', models.CharField(max_length=100)),
                ('Offer', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FootballItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_item', models.CharField(max_length=200)),
                ('item_type', models.CharField(choices=[('football', 'football'), ('Goal Post', 'Goal Post'), ('pad', 'pad'), ('shoes', 'shoes'), ('fullkit', 'fullkit'), ('glovse', 'glovse'), ('jersy', 'jersy'), ('select', 'select')], default='select', max_length=100)),
                ('item_image', models.ImageField(upload_to='sports/football/')),
                ('note', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('warranty', models.CharField(max_length=100)),
                ('Offer', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('user_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=16, unique=True)),
                ('wallet_amount', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SportsItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badminton_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sportsadmin.badmintonitemmodel')),
                ('carromchess_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sportsadmin.carromchessitemmodel')),
                ('cricket_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sportsadmin.cricketitemsmodel')),
                ('football_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sportsadmin.footballitemsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Order_items_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('user', models.CharField(max_length=130)),
                ('date', models.DateField(auto_now=True)),
                ('address', models.CharField(max_length=300)),
                ('pincode', models.CharField(max_length=6)),
                ('phonenumber', models.CharField(max_length=10)),
                ('status_order', models.CharField(choices=[('ordered', 'ordered'), ('packed', 'packed'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='ordered', max_length=50)),
                ('Order_Items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sportsadmin.sportsitemmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.CharField(max_length=1000)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sportsadmin.order_items_model')),
            ],
        ),
        migrations.CreateModel(
            name='Compalaines_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_img', models.ImageField(upload_to='sports/complaints/')),
                ('complaint_order', models.CharField(max_length=1000)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sportsadmin.order_items_model')),
            ],
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=130)),
                ('date', models.DateField(auto_now=True)),
                ('status_order', models.CharField(choices=[('cart', 'cart'), ('order placed', 'orderplaced'), ('buyed', 'buyed'), ('waiting user response', 'waiting user response'), ('canceled from cart', 'canceled from cart')], default='cart', max_length=50)),
                ('Items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sportsadmin.sportsitemmodel')),
            ],
        ),
    ]
