# Generated by Django 3.2 on 2021-07-09 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Creation_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_item', models.CharField(max_length=200)),
                ('item_image', models.ImageField(upload_to='sports/images')),
                ('note', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('warranty', models.CharField(max_length=100)),
                ('Offer', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sports_Catagory_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_sports', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('user_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=16, unique=True)),
                ('wallet_amount', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=100, unique=True)),
                ('sports_Model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sportsadmin.sports_catagory_model')),
            ],
        ),
        migrations.CreateModel(
            name='Order_items_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('user', models.CharField(max_length=130)),
                ('date', models.DateField(auto_now=True)),
                ('address', models.CharField(max_length=300)),
                ('pincode', models.CharField(max_length=6)),
                ('phonenumber', models.CharField(max_length=10)),
                ('status_order', models.CharField(choices=[('ordered', 'ordered'), ('packed', 'packed'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='ordered', max_length=50)),
                ('Order_Items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sportsadmin.item_creation_model')),
            ],
        ),
        migrations.AddField(
            model_name='item_creation_model',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sportsadmin.product_model'),
        ),
        migrations.AddField(
            model_name='item_creation_model',
            name='sports_catgory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sportsadmin.sports_catagory_model'),
        ),
        migrations.CreateModel(
            name='Feedback_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.CharField(max_length=1000)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sportsadmin.order_items_model')),
            ],
        ),
        migrations.CreateModel(
            name='Compalaines_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_img', models.ImageField(upload_to='sports/complaints/')),
                ('complaint_order', models.CharField(max_length=1000)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sportsadmin.order_items_model')),
            ],
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=130)),
                ('date', models.DateField(auto_now=True)),
                ('status_order', models.CharField(choices=[('cart', 'cart'), ('order placed', 'orderplaced'), ('buyed', 'buyed'), ('waiting user response', 'waiting user response'), ('canceled from cart', 'canceled from cart')], default='cart', max_length=50)),
                ('Items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sportsadmin.item_creation_model')),
            ],
        ),
    ]
